services:
  web:
    image: pnginxweb
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/sweb/nginx/Dockerfile
    container_name: ${NOMBRE}
    ports:
      - "${PORT_WEB}:80"
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netcarontewebnginx:
          ipv4_address: ${IP}

networks:
  netcarontewebnginx:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}