services:
  web:
    build:
      context: /home/rocio/Devops/Docker/Caronte
      dockerfile: dockerfiles/base/ubbase
      args: #Variables en Dockerfile para la construccion (build) de la imagen
      - USUARIO=rocio
      - PASSWORD=1234
    container_name: ctpbase
