services:
  web:
    image: pnginxweb:latest 
    
    
    
    container_name: ${NOMBRE}
    ports:
      - "${PORT_WEB}:80" 
      
    env_file:
      - ./.env 
      
    volumes:
      - ../../portfolio/src:/var/www/html 
      - ./logs:/root/logs 
      
    networks:
      netcarontewebnginx:
        ipv4_address: ${IP}

networks:
  netcarontewebnginx:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}