services:
  web:
    build:
      context: /home/rocio/Devops/Docker/Caronte
      dockerfile: dockerfiles/base/ubbase
      args:
        USUARIO: rocio
    container_name: ctpbase
    environment:
      - USUARIO=rocio
