services:
  web:
    build: 
      context: ${CONTEXTO}
      #args: #variables en dockerfile para la construcción de la imagen
      #  - USUARIO=rocio
      dockerfile: ./dockerfiles/base/ubbase
    container_name: ${NOMBRE}
    ports:
      - "${PORT_SSH}:${PORT_SSH}"
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netcaronte:
          ipv4_address: ${IP}

networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}